### PR TITLE
Upgraded to langchain 0.3.x

### PR DESCRIPTION
**Pull request by patcheng**
Description:
Langchain 0.3.x upgraded pydantic from v1 to v2, so need to migrate this project's to use Pydantic v2.

I upgraded langchain packages to 0.3.x. They no longer supports Python 3.8, so upgraded that as well.
Followed commit message https://github.com/langchain-ai/langchain/pull/26443 and followed the steps in https://github.com/eyurtsev/migrate-pydantic/tree/main?tab=readme-ov-file.

Fixed up various model so the tests passed.

Some noteable changes:
* The order of execution for validator changes between v1 and v2.
* also, seems like validator with the same name is base class is not being called anymore, so need to rename the method.

Ran `make test` and everything pass.
Ran `make lint` and fixed errors related to the change, and some obvious errors. There are still some errors that might be existing?
Ran `make format`

I tried to do each step as a separate commit. Hopefully makes it slightly easier to review.

### CODE REVIEW

**Comment by pprados** [comment]
Thanks!

To validate this PR, the `make validate` command must not return any errors. Can you fix the last points?

**Comment by patcheng** [comment]
ok. `test`, `lint`, `format` and `validate` are all passing.

**Comment by pprados** [comment]
Very good job !

**Comment by pprados** [comment]
The version v0.3.0 is published!

**Pull request merged**
